{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"GetCollectionTab\",\"Collection\",\"SWU-DB Dataset\",\"GetSWU-DBSet\",\"SWU-DB Sets\",\"SWU-DB Aspects\",\"SWU-DB Traits\",\"SWU-DB Arenas\",\"SWU-DB Keywords\",\"SWU Tracker\",\"Expansions\",\"Aspects\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.131.1203.0 (24.07)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "fastCombine": true,
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "GetSWU-DBSet",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "  Source = (SetID as text) =>",
          "    let ",
          "      Source = Json.Document(Web.Contents(\"https://api.swu-db.com/cards/\" & SetID)), ",
          "      #\"Converted to Table\" = Table.FromRecords({Source}), ",
          "      #\"Removed Columns\" = Table.RemoveColumns(#\"Converted to Table\", {\"total_cards\"}), ",
          "      #\"Expanded data\" = Table.ExpandListColumn(#\"Removed Columns\", \"data\"), ",
          "      #\"Expanded data1\" = Table.ExpandRecordColumn(",
          "        #\"Expanded data\", ",
          "        \"data\", ",
          "        {",
          "          \"Set\", ",
          "          \"Number\", ",
          "          \"Name\", ",
          "          \"Subtitle\", ",
          "          \"Type\", ",
          "          \"Aspects\", ",
          "          \"Traits\", ",
          "          \"Arenas\", ",
          "          \"Cost\", ",
          "          \"Power\", ",
          "          \"HP\", ",
          "          \"FrontText\", ",
          "          \"EpicAction\", ",
          "          \"DoubleSided\", ",
          "          \"BackText\", ",
          "          \"Rarity\", ",
          "          \"Unique\", ",
          "          \"Keywords\", ",
          "          \"Artist\", ",
          "          \"FrontArt\", ",
          "          \"BackArt\", ",
          "          \"VariantType\", ",
          "          \"MarketPrice\", ",
          "          \"FoilPrice\"",
          "        }, ",
          "        {",
          "          \"Expansion Code\", ",
          "          \"Number\", ",
          "          \"Name\", ",
          "          \"Subtitle\", ",
          "          \"Type\", ",
          "          \"Aspects\", ",
          "          \"Traits\", ",
          "          \"Arenas\", ",
          "          \"Cost\", ",
          "          \"Power\", ",
          "          \"HP\", ",
          "          \"Front Text\", ",
          "          \"Epic Action\", ",
          "          \"Double Sided\", ",
          "          \"Back Text\", ",
          "          \"Rarity\", ",
          "          \"Is Unique\", ",
          "          \"Keywords\", ",
          "          \"Artist\", ",
          "          \"Front Art\", ",
          "          \"Back Art\", ",
          "          \"Variant Type\", ",
          "          \"Market Price\", ",
          "          \"Foil Price\"",
          "        }",
          "      ), ",
          "      #\"Add Card Number\" = Table.AddColumn(",
          "        #\"Expanded data1\", ",
          "        \"Card Number\", ",
          "        each Text.PadStart([Number], 3, \"0\"), ",
          "        type text",
          "      ), ",
          "      #\"Added Custom\" = Table.AddColumn(",
          "        #\"Add Card Number\", ",
          "        \"Card Id\", ",
          "        each [Expansion Code] & \"-\" & [Card Number]",
          "      ), ",
          "      #\"Changed Type\" = Table.TransformColumnTypes(",
          "        #\"Added Custom\", ",
          "        {",
          "          {\"Expansion Code\", type text}, ",
          "          {\"Number\", Int64.Type}, ",
          "          {\"Name\", type text}, ",
          "          {\"Subtitle\", type text}, ",
          "          {\"Type\", type text}, ",
          "          {\"Cost\", Int64.Type}, ",
          "          {\"Power\", Int64.Type}, ",
          "          {\"HP\", Int64.Type}, ",
          "          {\"Front Text\", type text}, ",
          "          {\"Epic Action\", type text}, ",
          "          {\"Double Sided\", type logical}, ",
          "          {\"Back Text\", type any}, ",
          "          {\"Rarity\", type text}, ",
          "          {\"Is Unique\", type logical}, ",
          "          {\"Artist\", type text}, ",
          "          {\"Front Art\", type text}, ",
          "          {\"Back Art\", type text}, ",
          "          {\"Variant Type\", type text}, ",
          "          {\"Market Price\", type number}, ",
          "          {\"Foil Price\", type number}",
          "        }",
          "      )",
          "    in",
          "      #\"Changed Type\"",
          "in",
          "  Source"
        ],
        "kind": "m",
        "lineageTag": "0dda31eb-9ddb-4416-b641-f183ba026ae0",
        "queryGroup": "SWU-DB"
      },
      {
        "name": "SWU-DB Dataset",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    CombinedResults=Table.Combine({#\"GetSWU-DBSet\"(\"sor\"),#\"GetSWU-DBSet\"(\"shd\")})",
          "in",
          "    CombinedResults"
        ],
        "kind": "m",
        "lineageTag": "53732d62-40d7-4206-a139-6067ea1da786",
        "queryGroup": "SWU-DB"
      },
      {
        "name": "GetCollectionTab",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (ExpansionCode as text) => let",
          "        Source = GoogleSheets.Contents(#\"SWU Tracker\"),",
          "        #\"SHD\" = Source{[name=ExpansionCode,ItemKind=\"Table\"]}[Data],",
          "        #\"Promoted Headers\" = Table.PromoteHeaders(SHD, [PromoteAllScalars=true]),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Promoted Headers\",{\"Card Number\", \"Normal\", \"Foil\"}),",
          "        #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Other Columns\",{ {\"Card Number\", Int64.Type},{\"Normal\", Int64.Type}, {\"Foil\", Int64.Type}}),",
          "        #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"Card Id\", each ExpansionCode &\"-\" & Text.PadStart(Number.ToText([Card Number]),3,\"0\"))",
          "    in",
          "        #\"Added Custom\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "e5e7b3c1-9e47-4679-b98c-65202361b80d"
      },
      {
        "name": "SWU Tracker",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"https://docs.google.com/spreadsheets/d/1f6evlTIbbhwZl9gSv9WaA1RlJsS-5Z99Qev1PUYYONg/edit?gid=1753084144#gid=1753084144\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "0eb73c22-99f2-47f3-be78-036c6f0186e0"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "5"
          }
        ],
        "folder": "SWU-DB"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "5"
          }
        ],
        "folder": "Master"
      }
    ],
    "relationships": [
      {
        "name": "6dc0ed6b-057a-794b-727d-7890971060da",
        "fromColumn": "Card Id",
        "fromTable": "SWU-DB Aspects",
        "toColumn": "Card Id",
        "toTable": "SWU-DB Sets"
      },
      {
        "name": "c286bea5-30b5-88ca-f263-14d9c45806f8",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Card Id",
        "fromTable": "SWU-DB Arenas",
        "toColumn": "Card Id",
        "toTable": "SWU-DB Sets"
      },
      {
        "name": "aab4324d-8ca3-70bc-a4a3-5ff66b9ac385",
        "fromColumn": "Card Id",
        "fromTable": "SWU-DB Keywords",
        "toColumn": "Card Id",
        "toTable": "SWU-DB Sets"
      },
      {
        "name": "AutoDetected_a815b09a-6852-44fb-a8ca-973c6b48205a",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Card Id",
        "fromTable": "Collection",
        "toColumn": "Card Id",
        "toTable": "SWU-DB Sets"
      },
      {
        "name": "9673d0b9-b4fe-43e4-8c7c-56bbd0f589b2",
        "fromColumn": "Release Date",
        "fromTable": "Expansions",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_3914b327-f24d-4d2f-9199-0b435a9a3cca"
      },
      {
        "name": "13f049d4-4900-7580-1848-aa053a96f22e",
        "fromColumn": "Aspects",
        "fromTable": "SWU-DB Aspects",
        "toColumn": "Aspect",
        "toTable": "Aspects"
      },
      {
        "name": "04ee78ea-30a3-1941-5b1f-5e350da3b36d",
        "fromColumn": "Expansion Code",
        "fromTable": "SWU-DB Sets",
        "toColumn": "Code",
        "toTable": "Expansions"
      },
      {
        "name": "f8d5b0d4-d101-c095-6aa7-492cc7bf12c5",
        "fromColumn": "Card Id",
        "fromTable": "SWU-DB Traits",
        "toColumn": "Card Id",
        "toTable": "SWU-DB Sets"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_92989b07-0625-44ef-afba-ae60539b07ee",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e924c8fe-a960-4f52-bf1c-c91439f24bd3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "0a0b6cfb-de9d-4e14-9ebd-5df453aee94c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "6b3bb61d-eefc-4726-980d-85a581632bbc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "638f8a24-f29b-4463-ae0e-28da0b749b17",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "3ad3756a-29d3-43c5-abf5-e4a2b248f0ca",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "1c27d541-39a5-432b-b371-3c57742dfddf",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "d411d04c-c49e-438a-978d-07a83625ca41",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "8215792a-5fce-474e-8f80-10024e81896e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "17e60891-0e19-4314-af2e-9c751473c254",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "66cabadc-e396-444f-9796-e63e5c9b6490",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "c371f2f2-3466-4c54-9112-4b1801e070a6",
                "ordinal": 3
              }
            ],
            "lineageTag": "30e22ca9-3c7a-4858-a2f8-a898ab7928e7"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "0d3373ea-39b5-453a-91d7-26ed930177ef",
        "partitions": [
          {
            "name": "DateTableTemplate_92989b07-0625-44ef-afba-ae60539b07ee",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Collection",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Foil",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "56509ce4-b1d1-497e-87a9-869b1cd7c465",
            "sourceColumn": "Foil",
            "summarizeBy": "sum"
          },
          {
            "name": "Card Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a8adf39e-f4b5-408e-b141-5e241187cb11",
            "sourceColumn": "Card Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Normal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a0a99985-9303-409d-9b17-69668dfe4e67",
            "sourceColumn": "Normal",
            "summarizeBy": "sum"
          },
          {
            "name": "Card Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "320089ce-75f4-4265-a334-c1c0014c95eb",
            "sourceColumn": "Card Id",
            "summarizeBy": "none"
          },
          {
            "name": "Total Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "Collection[Normal] * RELATED('SWU-DB Sets'[Market Price]) + Collection[Foil] * RELATED('SWU-DB Sets'[Foil Price])",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "isDataTypeInferred": true,
            "lineageTag": "4f2c90a7-dea2-42a1-adda-1e83863ee532",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Number of cards",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "Collection[Foil]+Collection[Normal]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "e241eae1-90d2-44a1-be11-bbec77bd1bb2",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Normal Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "Collection[Normal] * RELATED('SWU-DB Sets'[Market Price])",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "isDataTypeInferred": true,
            "lineageTag": "9abb2814-aa71-4d3c-8db0-f246622bf2d3",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Foil Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "Collection[Foil] * RELATED('SWU-DB Sets'[Foil Price])",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "isDataTypeInferred": true,
            "lineageTag": "399b1d0f-cc50-4940-9cf3-932527027e5b",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "b2d626f4-9e40-42ee-8492-9b0c1067d127",
        "partitions": [
          {
            "name": "Collection",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.Combine({GetCollectionTab(\"sor\"), GetCollectionTab(\"shd\")})",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SWU-DB Sets",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Expansion Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad4f59c4-7d5f-4ee4-bee5-e7302583277e",
            "sourceColumn": "Expansion Code",
            "summarizeBy": "none"
          },
          {
            "name": "Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1a57fc9a-0e76-41a4-88b3-d9c8b71e2bd0",
            "sourceColumn": "Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "299da9e9-1ab5-4852-835b-1efdd1764048",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Subtitle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a07e43f-9b19-47cb-8cd2-806974fd9cab",
            "sourceColumn": "Subtitle",
            "summarizeBy": "none"
          },
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84e6b381-b42a-434e-8958-3d5b4b95c145",
            "sourceColumn": "Type",
            "summarizeBy": "none"
          },
          {
            "name": "Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "808a39d3-e899-414d-9846-17831a372707",
            "sourceColumn": "Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Power",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "832aa7d5-4f7a-417b-9b3a-41c82dddc336",
            "sourceColumn": "Power",
            "summarizeBy": "sum"
          },
          {
            "name": "HP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6124ceb4-1219-402d-8d82-76bd721a5935",
            "sourceColumn": "HP",
            "summarizeBy": "sum"
          },
          {
            "name": "Front Text",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "660b661d-369b-4dc6-a37d-c74c56617dae",
            "sourceColumn": "Front Text",
            "summarizeBy": "none"
          },
          {
            "name": "Epic Action",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7c91ee3-c33f-41e6-a2b9-0ad17df113ed",
            "sourceColumn": "Epic Action",
            "summarizeBy": "none"
          },
          {
            "name": "Double Sided",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "d144ce8b-5601-4d2f-a85c-bb58548a844d",
            "sourceColumn": "Double Sided",
            "summarizeBy": "none"
          },
          {
            "name": "Back Text",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4744e2d2-a396-4f2f-9d32-ed8470255258",
            "sourceColumn": "Back Text",
            "summarizeBy": "none"
          },
          {
            "name": "Rarity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce7eb254-dd4b-487b-b647-d0752a6431da",
            "sourceColumn": "Rarity",
            "summarizeBy": "none"
          },
          {
            "name": "Is Unique",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "1e5f3e43-d433-4d94-8e5a-f71894671731",
            "sourceColumn": "Is Unique",
            "summarizeBy": "none"
          },
          {
            "name": "Artist",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "923f2640-6f0e-4da6-9c60-b71fb50ce4a2",
            "sourceColumn": "Artist",
            "summarizeBy": "none"
          },
          {
            "name": "Front Art",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "c41c249d-c542-49ed-8145-4e94f897e8ad",
            "sourceColumn": "Front Art",
            "summarizeBy": "none"
          },
          {
            "name": "Back Art",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "9e606188-23d6-4cf5-84aa-fe254a517373",
            "sourceColumn": "Back Art",
            "summarizeBy": "none"
          },
          {
            "name": "Variant Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1337bab7-b5a3-478d-8dd1-10b2cee7da25",
            "sourceColumn": "Variant Type",
            "summarizeBy": "none"
          },
          {
            "name": "Market Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "3f58031a-23e4-4d94-8cb9-b9a9c5443f9d",
            "sourceColumn": "Market Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Foil Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "b023f31b-d5fe-4a16-8ee6-037886b600dc",
            "sourceColumn": "Foil Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Card Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f5c558e-9d2a-481a-8b7d-6981691b2098",
            "sourceColumn": "Card Number",
            "summarizeBy": "none"
          },
          {
            "name": "Card Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ae988cd-fea8-4f00-a460-2a57f49f3e0d",
            "sourceColumn": "Card Id",
            "summarizeBy": "none"
          },
          {
            "name": "Number of cards",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "If(ISBLANK([Foil Price]), 1, 2)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "63f61f23-51ba-4825-b412-cafb8518380e",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "25712e69-f991-422d-8770-d04cdf07ba34",
        "partitions": [
          {
            "name": "SWU-DB Sets",
            "mode": "import",
            "queryGroup": "SWU-DB",
            "source": {
              "expression": [
                "let",
                "    Source = #\"SWU-DB Dataset\",",
                "    #\"Removed Columns\" = Table.RemoveColumns(Source,{\"Aspects\", \"Traits\", \"Arenas\", \"Keywords\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SWU-DB Aspects",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Aspects",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a4a4670-a3bf-45bc-97a6-22addeb89c0d",
            "sourceColumn": "Aspects",
            "summarizeBy": "none"
          },
          {
            "name": "Card Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5df34cc9-6790-46e5-8038-e434052bc162",
            "sourceColumn": "Card Id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0af9a256-3802-4740-8934-78704e17385d",
        "partitions": [
          {
            "name": "SWU-DB Aspects",
            "mode": "import",
            "queryGroup": "SWU-DB",
            "source": {
              "expression": [
                "let",
                "    Source = #\"SWU-DB Dataset\",",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Aspects\", \"Card Id\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Other Columns\", each [Aspects] <> null and [Aspects] <> \"\"),",
                "    #\"Expanded Aspects\" = Table.ExpandListColumn(#\"Filtered Rows\", \"Aspects\")",
                "in",
                "    #\"Expanded Aspects\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SWU-DB Traits",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Traits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f25a05d7-6941-4d33-9d05-b224862122f4",
            "sourceColumn": "Traits",
            "summarizeBy": "none"
          },
          {
            "name": "Card Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "036a0aaa-e71a-49da-9691-18dacb6e77e4",
            "sourceColumn": "Card Id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3a7d5575-422a-4e52-9156-e382af6aaf41",
        "partitions": [
          {
            "name": "SWU-DB Traits",
            "mode": "import",
            "queryGroup": "SWU-DB",
            "source": {
              "expression": [
                "let",
                "    Source = #\"SWU-DB Dataset\",",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Traits\", \"Card Id\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Other Columns\", each [Traits] <> null and [Traits] <> \"\"),",
                "    #\"Expanded Aspects\" = Table.ExpandListColumn(#\"Filtered Rows\", \"Traits\")",
                "in",
                "    #\"Expanded Aspects\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SWU-DB Arenas",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Arenas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3c4cb18-9532-4340-a6ff-e0b54c94b808",
            "sourceColumn": "Arenas",
            "summarizeBy": "none"
          },
          {
            "name": "Card Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb90a7da-187a-481c-9861-4b77d59c20bf",
            "sourceColumn": "Card Id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "81213ae0-e400-4651-9b4b-e131163aebd8",
        "partitions": [
          {
            "name": "SWU-DB Arenas",
            "mode": "import",
            "queryGroup": "SWU-DB",
            "source": {
              "expression": [
                "let",
                "    Source = #\"SWU-DB Dataset\",",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Arenas\", \"Card Id\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Other Columns\", each [Arenas] <> null and [Arenas] <> \"\"),",
                "    #\"Expanded Aspects\" = Table.ExpandListColumn(#\"Filtered Rows\", \"Arenas\")",
                "in",
                "    #\"Expanded Aspects\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SWU-DB Keywords",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Keywords",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb9beeb7-7ac3-4b26-8577-2c883ebfa47c",
            "sourceColumn": "Keywords",
            "summarizeBy": "none"
          },
          {
            "name": "Card Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84dfb6b2-36b4-4c12-95fe-1bf6c6d93910",
            "sourceColumn": "Card Id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9d5d6953-3cb7-4bd5-8342-64b91995ec9b",
        "partitions": [
          {
            "name": "SWU-DB Keywords",
            "mode": "import",
            "queryGroup": "SWU-DB",
            "source": {
              "expression": [
                "let",
                "    Source = #\"SWU-DB Dataset\",",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Keywords\", \"Card Id\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Other Columns\", each [Keywords] <> null and [Keywords] <> \"\"),",
                "    #\"Expanded Aspects\" = Table.ExpandListColumn(#\"Filtered Rows\", \"Keywords\")",
                "in",
                "    #\"Expanded Aspects\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Expansions",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04c5bded-f8ff-43d7-a2ff-98e24b5e5e56",
            "sourceColumn": "Code",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "2bbb3570-d56b-469a-a742-2e3e691add15",
            "sortByColumn": "Release Date",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Logo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "36b3f1e7-3d29-40b8-98bd-0033b57c491e",
            "sourceColumn": "Logo",
            "summarizeBy": "none"
          },
          {
            "name": "Release Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0bec3570-2429-454c-a524-287b9c26ce10",
            "sourceColumn": "Release Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_3914b327-f24d-4d2f-9199-0b435a9a3cca"
                },
                "isDefault": true,
                "relationship": "9673d0b9-b4fe-43e4-8c7c-56bbd0f589b2"
              }
            ]
          }
        ],
        "lineageTag": "62180a3d-dc84-445b-9aae-89c77b34bf9f",
        "partitions": [
          {
            "name": "Expansions",
            "mode": "import",
            "queryGroup": "Master",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"tc/BasJAEAbgVwkBb5Kd7kYTC6F4qYIHwRx6sLJMsqNJu8nG3Q3Rt2+s9VZ6K8xhmH8G5tvvQ2dsOA3zDu1nYI7BjgrSujbtOKy879wzY86jHdC6vtV1U3tSUWkaJlu6eFY3eKKX3urse3silhP+Olap2ujXu3ucv63lmlCRlfl2Jzd0lUvrZQyFSsTsiIvoozu99wB8PmQijeHen7NkNj4GgkHKOPA4PExHQqVuhAqVGdwN4SsKVqjxcv1/BfAH5IFIy2IucKGexN+IhAH/QRy+AA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Code = _t, Name = _t, Logo = _t, #\"Release Date\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Code\", type text}, {\"Name\", type text}, {\"Logo\", type text}, {\"Release Date\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_3914b327-f24d-4d2f-9199-0b435a9a3cca",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "468ad050-9320-45b0-9046-fc958297b168",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "49d97da9-98d3-46ad-ae45-8e15e588cc06",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "1cd05409-a69e-483f-988e-df4c11b22e23",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "855d4717-5dbf-4235-92cc-1fdf76c67f57",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "d24bad08-29a0-45a8-a1e8-89b27a2eef60",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "d1fc906a-40aa-4924-aebc-a1fe3db61c3a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "e38435ab-e438-4944-a745-4cc0402051c2",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f530ff8f-6fbb-4b6e-96d1-5d03732671ae",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "0bcae594-bb46-4b92-bd05-0ce9a6ace9df",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "36dc244f-a9c2-4de1-a479-dc38a723d8ad",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "30eaba00-e88a-444b-a304-86c9c4ac9854",
                "ordinal": 3
              }
            ],
            "lineageTag": "37d44fc5-c6c4-48d4-9d35-0376b0989161"
          }
        ],
        "isHidden": true,
        "lineageTag": "4f81dd4d-48cc-455e-b329-ddcc72910260",
        "partitions": [
          {
            "name": "LocalDateTable_3914b327-f24d-4d2f-9199-0b435a9a3cca",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Expansions'[Release Date])), 1, 1), Date(Year(MAX('Expansions'[Release Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Aspects",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Aspect",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70d02fae-cb49-4a35-9eab-4c71b2675620",
            "sourceColumn": "Aspect",
            "summarizeBy": "none"
          },
          {
            "name": "Logo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c255f06c-77c8-4d77-bf34-fe5c8253d905",
            "sourceColumn": "Logo",
            "summarizeBy": "none"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b527c00a-d596-4518-b8af-5a4bdf0f78d2",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6e7e2f3c-0e27-43e4-a5b9-d373de4b85e8",
        "partitions": [
          {
            "name": "Aspects",
            "mode": "import",
            "queryGroup": "Master",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"rZXbihtHEIZfpRD4TtYakxOGxTgBk8uAjXOxMaa2p2amsj3d4z5oPHd5jbxensR/T7dsjGyBia7UGo3q8NVff9/d7d7ooJadkd1+N6Y0x2c3NzFxWDjE7KxOmqQ7GD/dvHPyId3oxIM8z8HePnr6Uo13EZ8cZzEJh+Mp2mF2w1/5yZOnPy23P/xST+9vf/4RWf6wvFInvbioR7ErLZpGSqMQ36vVtFLyNApb6rgk21OQyR8FX90gwedI2WmK1Ac/0Yxoe2LX0Rx8QhW0+hzonqPUF8TJtBKnxOYhHuj1qJFqvYTTLKEvx96HLZSESMvoyeqD0MxJxaXth5hWKxFlciLDDmG7HITkKG6rvRPurEpMCB4524RctHu7v9v95qcJ9V2Fr6mxLtB9YYxYCZykgggS8WFQemFk2FrKs3dkPQj6vqFE9zEFcQNaqf3U5whBbAN6W2lkzEDdRqNx1FjnVnEimhm9GjmjuTAoYqqYYlhGsVP5mwbyM0oB4Vg1wDQBHkRB955DmahEKWJqJF8MA55E9e4qMPlTuEs8N+HU+ib+oFOGpPpeDZRh1g1qp3Ekn9MnplW3Z1pjQj7Ip9dzvaHVXgL1HNPjmY10e7wmYT3T3j1CPOCIPRjGzwD/++fftlNt0iO6LpSnKPZY/uyXgvSoJvlQ9gFvrWR8TIcm0+ycuuE6Mq2xLmHteN4kUaqImjJWDar0VXz9yRVmv2BBs92TTpN0WmQN+shSuzwRT97buEHFMEKeE7JX/Z8IAVAsMN25B/BnF/j2ZFAqxIJYHb3Pah7sZlOYAybaiJf9gDMgxVJGiThoLo2llC/lDuzZdtsQl/bTUnZqm8PvsDiN01XmMNZYF+bwUoex9SyQ3dbI3zmmssXbBAxU06TXo9XieWVCxWx58E5jGwCevUKd9CcKpSgBVngGusn/q+awUWjJPMUMVCF94euoD4LHi6A1qpXNHmKj2wz+LKXvEwxtZg3SNZNxNcbJtDCwLW/D/0atZXXrla7DGuzCAH5F4bY6Ji4NhIPCN9VfxA9k303/W1fdyZzb3QLnGJAgTIhR7oVFBVo9LSJMBhdFNqm4dNvEA70CF8vbkjT57lHT/xjE248=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Aspect = _t, Logo = _t, Description = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Aspect\", type text}, {\"Logo\", type text}, {\"Description\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}